### ISSUE TITLE
Cannot change type of Either "Left" in chain

### ISSUE THREAD

**Issue by RLovelett** [nythrox/purifree#37]
It seems that the `Either` `chain` method signature is incorrect (or at the very least incongruent with Purify's signature).

* Purifree: [`chain<R2>(f: (value: R) => Either<L, R2>): Either<L, R2>`](https://github.com/nythrox/purifree/blob/a00b25ae82745af76939383d5ae6880807f4d89a/src/Either.ts#L46)
* Purify: [`chain<L2, R2>(f: (value: R) => Either<L2, R2>): Either<L | L2, R2>`](https://github.com/gigobyte/purify/blob/6160b301c7fa4acb94a42344939d1600f2303753/src/Either.ts#L28)

This means that this code compiles in Purify but cannot in Purifree.

```typescript
Right(1)
  .chain(() => Left('nope'));
```

`Type 'Either<string, never>' is not assignable to type 'Either<never, never>'. Type 'string' is not assignable to type 'never'.`

**Comment by nythrox** [comment]
You're right! Sorry for the late response, I'll update it soon.

**Comment by nythrox** [comment]
Fixed now that we've updated Purify's version :)
