### ISSUE TITLE
Use Module Augmentation

### ISSUE THREAD

**Issue by ikezedev** [nythrox/purifree#44]
This is to keep updated with the changes from Purify without having to reinvent the wheel. This will be populated with issues that need to be closed for this changed to be marked completed and published.

- [x] Migrate all ADTs to use purify ADTs
- [x] Expose new pointfree methods
- [x] Ensure all tests are passing
- [x] Add new tests where necessary
- [x] close #41 as resolved
- [x] Drop use of ts-toolbelt

**Comment by nythrox** [comment]
Merged #45 ❤️
